on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  # extract_version:
  #   name: Extract version from tag
  #   runs-on: ubuntu-latest
  #   outputs:
  #     version: ${{ steps.extract_version.outputs.version }}
  #   steps:
  #   - name: checkout
  #     uses: actions/checkout@v3
  #     with:
  #       fetch-depth: 0
  #   - name: extract version
  #     uses: damienaicheh/extract-version-from-tag-action@v1.1.0
  #   - name: save version
  #     id: extract_version
  #     run: |
  #       echo "version=$MAJOR.$MINOR.$PATCH"
  #       echo "version=$MAJOR.$MINOR.$PATCH" >> "$GITHUB_OUTPUT"
  export_game_release:
    uses: ./.github/workflows/build-and-upload.yml
    # needs: extract_version
    with:
      project_name: ${{ vars.PUBLIC_PROJECT_NAME }}
      version: ${{ github.ref_name }}
    secrets:
      BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
      UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
      UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
  